# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

services:
  frc-site:
    image: micw1417/frc5431.com:website
    restart: unless-stopped
    container_name: frc-site
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
  backend:
    image: micw1417/frc5431.com:backend

    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    environment:
      NODE_ENV: production