services:
  frc-site:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: no
    environment:
      NODE_ENV: production
      PORT: ${FRONTEND_PORT}
    expose:
      - ${FRONTEND_PORT}

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      NODE_ENV: production
      PORT: ${BACKEND_PORT}
    expose:
      - ${BACKEND_PORT}
  caddy:
    image: caddy:2.10
    restart: unless-stopped
    depends_on:
      - frc-site
      - backend
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
      - ./frontend/dist:/srv/frontend
    env_file: .env
    environment:
      - DOMAIN=${DOMAIN}
    ports:
      - "80:80"
      - "443:443"

volumes:
  caddy_data:
  caddy_config:
