services:
  frc-site:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        HOST: ${HOST}
        VITE_BACKEND_URL: ${VITE_BACKEND_URL}
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: ${FRONTEND_PORT}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      NODE_ENV: production
      PORT: ${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"